### ISSUE TITLE
How To Include and Use in Stencil App

### ISSUE THREAD

**Issue by TheBrockEllis** [seanwuapps/stencil-loading-spinner#1]
Hi there! While I understand that this may not be a direct issue with this particular component, I was curious on how you would include this amazing work in a stencil app and use it. Also, best practices for  making it conditionally displayed when content is loading. 

Thanks so much for your help!

**Comment by seanwuapps** [comment]
Hi @TheBrockEllis 
This component was developed during the early age of Stencil so there are things that could've been done better. 
As the official documentation says [here](https://stenciljs.com/docs/distribution) 

In a stencil-app-starter app
Run npm install my-name --save
Add { name: 'my-name' } to your collections (stencil.config.js)
Then you can use the element anywhere in your template, JSX, html etc

**Comment by seanwuapps** [comment]
and you can conditionally display it however you like, it's a html tag anyways
